package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_ASSIGNMENT_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u45/3627/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, April 30, 2015 12:31:44 PM PDT
*/

public interface ID_ASSIGNMENT_POLICY_ID
{

  /**
	 * The value representing ID_ASSIGNMENT_POLICY_ID.
	 */
  public static final int value = (int)(19L);
}
